// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOEMOJI_10_FONT_ID (952059440)
#define NOTOEMOJI_12_FONT_ID (-1534646981)
#define NOTOEMOJI_14_FONT_ID (1515630286)
#define NOTOEMOJI_16_FONT_ID (-1695995499)
#define NOTOSYMBOLS_10_FONT_ID (2107159717)
#define NOTOSYMBOLS_12_FONT_ID (-1176878313)
#define NOTOSYMBOLS_14_FONT_ID (832405228)
#define NOTOSYMBOLS_16_FONT_ID (-7011261)
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_8_FONT_ID (-1321080664)
#else
#define LEXENDDECA_8_FONT_ID (-607847335)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_9_FONT_ID (1590774326)
#else
#define LEXENDDECA_9_FONT_ID (-998073127)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_10_FONT_ID (538164236)
#else
#define LEXENDDECA_10_FONT_ID (-1272841049)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_12_FONT_ID (-281634069)
#else
#define LEXENDDECA_12_FONT_ID (-1512866966)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_14_FONT_ID (117406013)
#else
#define LEXENDDECA_14_FONT_ID (894667305)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_16_FONT_ID (391716658)
#else
#define LEXENDDECA_16_FONT_ID (1416238269)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_18_FONT_ID (496571505)
#else
#define LEXENDDECA_18_FONT_ID (992910623)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_20_FONT_ID (-140890231)
#else
#define LEXENDDECA_20_FONT_ID (509559279)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_8_FONT_ID (821472805)
#else
#define CHAREINK_8_FONT_ID (2135726846)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_9_FONT_ID (1522832619)
#else
#define CHAREINK_9_FONT_ID (-1067102375)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_10_FONT_ID (-1195026670)
#else
#define CHAREINK_10_FONT_ID (-709874216)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_12_FONT_ID (-940237256)
#else
#define CHAREINK_12_FONT_ID (2042625416)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_14_FONT_ID (1749129416)
#else
#define CHAREINK_14_FONT_ID (-19980631)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_16_FONT_ID (-809787149)
#else
#define CHAREINK_16_FONT_ID (184216235)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_18_FONT_ID (495487727)
#else
#define CHAREINK_18_FONT_ID (1782861482)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_20_FONT_ID (-142342320)
#else
#define CHAREINK_20_FONT_ID (-271291529)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_8_FONT_ID (1514174737)
#else
#define BITTER_8_FONT_ID (-155187596)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_9_FONT_ID (2085726412)
#else
#define BITTER_9_FONT_ID (111935037)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_10_FONT_ID (-423122438)
#else
#define BITTER_10_FONT_ID (-1878644540)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_12_FONT_ID (-533301290)
#else
#define BITTER_12_FONT_ID (973468287)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_14_FONT_ID (1641086884)
#else
#define BITTER_14_FONT_ID (-223611180)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_16_FONT_ID (1864693512)
#else
#define BITTER_16_FONT_ID (591062262)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_18_FONT_ID (-188611086)
#else
#define BITTER_18_FONT_ID (684575232)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_20_FONT_ID (-1898750376)
#else
#define BITTER_20_FONT_ID (-1019047570)
#endif
#define UI_10_FONT_ID (1524577939)
#define UI_12_FONT_ID (614158182)
#define SMALL_FONT_ID (-1620540724)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOEMOJI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOEMOJI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOEMOJI_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOEMOJI_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSYMBOLS_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSYMBOLS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSYMBOLS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSYMBOLS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
